### ISSUE TITLE
cannot delete some directories

### ISSUE THREAD

**Issue by rychlym** [ypid-bot/doublecmd#2]
Hello,
I have installed the version 0.7.8 beta on Windows 10. I found out, that it sometimes fails to delete directories, especially when deleting a directory referring to a local git repository.
(As workaround I usually run the classic windows file explorer, which successfully finish the deleting operation)
Have you the same issue and is there a better receipt to handle it?

**Comment by ypid** [comment]
Well, I have never had such behavior on GNU/Linux so https://getgnulinux.org/ would solve issues 😉 Other than that, this is the wrong issue tracker as stated: "Unofficial mirror of the Double Commander project". Interestingly only Windows folks seem to confuse this sometimes, no offense. Please refer to https://doublecmd.sourceforge.io/mediawiki/index.php/Making_a_bug_report
And please be specific. "sometimes fails to delete directories". Maybe quote the error message and find the debug log of doublecmd will probably be helpful. You are a developer yourself so you probably also deal with user bug reports.
Feel free to close this issue when you reported upstream. Thanks.
